version: '3.8'

services:
  joomla:
    image: joomla:${JOOMLA_VERSION}
    restart: always
    ports:
      - ${JOOMLA_PORT}:80
    expose:
      - 80
    environment:
      JOOMLA_DB_HOST: ${DATABASE_HOST}
      JOOMLA_DB_NAME: ${DATABASE_NAME}
      JOOMLA_DB_USER: ${DATABASE_USER}
      JOOMLA_DB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - './www:/var/www/html'
    networks:
      - joomla
  database:
    image: mysql:${MYSQL_VERSION}
    restart: always
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - 'database:/var/lib/mysql'
    networks:
      - joomla

volumes:
  database:
networks:
  joomla: